### ISSUE TITLE
About pretraining dataset

### ISSUE THREAD

**Issue by chenhang98** [ydchen0806/dbMiM#2]
Hi author, thanks for your excellent work. 
I'm trying to reproduce parts of your work. I noticed that you mentioned that your pre-training dataset is sampled from the FAFB dataset. Would you mind providing the pre-training dataset or the code or detailed way of sampling it?

**Comment by ydchen0806** [comment]
Thank you very much for your attention to our work. We apologize for not updating the code repository earlier due to issues related to internships and other commitments. Previously, we were unable to upload the pre-training dataset due to license restrictions. However, we have now obtained the necessary licensing permissions. Within the next three weeks, I will update the complete project repository and upload the dataset to Hugging Face.

**Comment by chenhang98** [comment]
Thanks. This is a good news. Look forward to your update. 👍

**Comment by ydchen0806** [comment]
Hello,

I have uploaded the pre-trained dataset to Hugging Face. You can find the download link in the README file. Please note our data usage license; once you apply for access, we will review and approve the request as soon as possible. Due to network upload speeds, the code and pre-trained weights will also be updated within the next two weeks.

**Comment by chenhang98** [comment]
Great! I have got the access. Are FAFB_crop_hdf_1.zip ~ FAFB_crop_hdf_7.zip corresponding to the FAFB pre-training dataset mentioned in the paper? I'm a bit confusing because the paper mentioned that the FAFB dataset has 60G images, while the 7 zip files are total about 120G.

**Comment by ydchen0806** [comment]
I'm sorry for the confusion. The quality of the dataset is indeed crucial for the pre-training setting. Therefore, in subsequent new work and collaborative projects, we have collected and cleaned more datasets, including more brain regions and species. This process took considerable effort and involved numerous copyright issues.

Back in 2022, we only used a 60GB sample from the FAFB dataset. You can achieve similar results to those mentioned in the paper by accessing the first four FAFB zip files from my link. Alternatively, you can use the additional pre-training data to achieve even better results. In our latest work, [TokenUnify](https://arxiv.org/abs/2405.16847), using all the datasets can yield nearly a 45% improvement, which was previously unattainable.

**Comment by chenhang98** [comment]
I see. Thanks for your reply.
